---
- name: httpd installation playbook
  hosts: apps
  become: true
  tasks: 
    - name: httpd install
      yum:
        name: httpd
        state: latest
    - name: update index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html
    - name: restart service
      service: 
        name: httpd
        state: restarted
    - name: check status
      command: systemctl status httpd
      register: status
    - name: print output
      debug:
        var: status
    